# Generated by Django 3.2.2 on 2021-11-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211124_1849'),
        ('articles', '0002_auto_20211124_2012'),
    ]

    operations = [
    ]
