# Generated by Django 3.2.2 on 2021-11-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_like_users'),
        ('articles', '0004_auto_20211124_2047'),
    ]

    operations = [
    ]
